create table public.sermons (
 id bigint generated by default as identity primary key,
 title text not null,
 speaker text not null,
 date date not null,
 image_url text not null,
 audio_url text not null,
 created_at timestamptz default now()
);
alter table public.sermons enable row level security;
create policy "read sermons" on public.sermons for select to anon,authenticated using (true);
create policy "add sermons" on public.sermons for insert to authenticated with check (true);
create policy "delete sermons" on public.sermons for delete to authenticated using (true);

insert into storage.buckets (id,name,public)
values ('sermons','sermons',true) on conflict (id) do nothing;

create policy "read sermon files" on storage.objects for select to anon,authenticated using (bucket_id='sermons');
create policy "upload sermon files" on storage.objects for insert to authenticated with check (bucket_id='sermons');
create policy "delete sermon files" on storage.objects for delete to authenticated using (bucket_id='sermons');
